[connection]
adb_path = "/opt/android-sdk/platform-tools/adb"
# preset = "PlayCover"
address = "192.168.240.112:5555"
config = "General"

[instance_options]
adb_lite_enabled = false
deployment_with_pause = false
kill_adb_on_exit = false
touch_mode = "MaaTouch"

[resource]
user_resource = false
