[[tasks]]
name = "启动"
type = "StartUp"
params = { client_type = "Bilibili", start_game_enabled = true }

[[tasks]]
type = "Recruit"

[tasks.params]
refresh = true
select = [4, 5]
confirm = [3, 4, 5]
skip_robot = false
recruitment_time = { '3' = 460 }
report_to_penguin = true

[[tasks]]
type = "Award"

[tasks.params]
award = true
mail = true
orundum = true
specialaccess = true


[[tasks]]
type = "Infrast"

[tasks.params]
mode = 20000
facility = [
  "Trade",
  "Reception",
  "Mfg",
  "Control",
  "Power",
  "Office",
  "Training",
  "Dorm",
]
drones = "PureGold"
# filename = "normal-ng.json"
# replenish = true
# continue_training = true

# [[tasks.variants]]
# condition = { type = "Time", start = "08:00:00", end = "11:59:59" }
# params = { plan_index = { default = 1, description = "index of plan" } }
#
# [[tasks.variants]]
# condition = { type = "Time", start = "12:00:00", end = "15:59:59" }
# params = { plan_index = { default = 2, description = "index of plan" } }
#
# [[tasks.variants]]
# condition = { type = "Time", start = "16:00:00", end = "23:59:59" }
# params = { plan_index = { default = 3, description = "index of plan" } }
#
# [[tasks.variants]]
# params = { plan_index = { default = 0, description = "index of plan" } }
